### ISSUE TITLE
Having issues getting it running

### ISSUE THREAD

**Issue by samcro1967** [ksurl/docker-autodelete-discord#22]
I am seeing the error message below in the log.  I am not able to get to http://osu.autodelete/discord_auto_delete/oauth/start.  http://osu.autodelete is setup in NPM to point to http://192.168.1.104:2022.  osu.autodelete is setup in AdGuard with a DNS rewrite and pointing at 192.168.1.104.

Any ideas?

**Logs**
```
From https://github.com/riking/AutoDelete
   fd67ac3..8cd5bdc  master     -> origin/master
Updating fd67ac3..8cd5bdc
Fast-forward
 README.md                                     | 12 ++++++++++++
 docs/prometheus-autodelete-aggregator.service |  2 +-
 2 files changed, 13 insertions(+), 1 deletion(-)
github.com/riking/AutoDelete/cmd/autodelete
[reap] waiting for insertion
[reap] waiting for insertion
url: http://osu.autodelete/discord_auto_delete/oauth/start
error while reporting to error log: HTTP 404 Not Found, {"message": "404: Not Found", "code": 0}
[LOG] AutoDelete started (-1/0).
```

**config.yml**
```
# see config.go "type Config" for more fields
clientid: "<redacted>"
clientsecret: "<redacted>"
bottoken: "<redacted>"
adminuser: "<redacted>"
http:
  listen: "0.0.0.0:2022"
  public: "http://osu.autodelete"
backlog_limit: 200
errorlog: "/app/logs/error.log"
statusmessage: "in the garbage"
```
**Docker Compose**
```
  autodelete:
    hostname: autodelete
    image: ksurl/autodelete-discord:latest
    container_name: autodelete
    restart: always
    ports:
      - 2022:2202
    volumes:
      - ${docker}/autodelete/config/config.yml:/app/config.yml
      - ${docker}/autodelete/data:/app/data
      - ${docker}/autodelete/logs:/app/logs
```
